### PR TITLE
Upgraded 4 gemfiles, .travis.yml file and .ruby-version file.

### PR DESCRIPTION
**Pull request by jasnow**
Upgraded 4 gemfiles, .travis.yml file and .ruby-version file.

Today the upgrade **broke** for edge Rails version (6.0.0.alpha) 
since this version **requires Ruby >= 2.4.1** so I recommend we merge
yesterday's (current) version and then handle Ruby upgrade separately.

### CODE REVIEW

**Comment by jasnow** [comment]
@ckdake -The problem mentioned above is Rails 3.x uses arel 3.0.3 which
is incompatible with Ruby 2.4.3+ (Cannot visit Integer) therefore the 
question is do we still need to support Rails 3.x?

**Comment by ckdake** [comment]
It would of course be nice to continue supporting Rails 3, I still have a handful of apps I've never upgraded that use setler, but I also haven't touched them in years.  If doing the ruby upgrade first gets us in a better place, I'd rather merge that than supporting Rails 6 alpha, but it also looks like Rails 3 has been end-of-lifed for years. What do you think?

**Comment by jasnow** [comment]
@ckdake - Removing Rails 3 support was the easier way forward. If you want to keep Rails 3 support, we can create a Github ticket for the "Rails edge" (Rails 6 alpha) upgrade support and I will no continuous ("daily"/regular) upgrades. Either way I would recommend merging this PR as the baseline.

**Comment by ckdake** [comment]
Lets go ahead and ditch Rails 3. Thanks!

**Comment by jasnow** [comment]
You might want to create a branch to "freeze" what we have currently.

**Comment by ckdake** [comment]
Given how straightforward the changelog is here, someone could just snag based on commit sha, right?

**Comment by jasnow** [comment]
Okay

**Pull request merged**
