### PR TITLE
Added simplecov for coverage analysis

### PR DESCRIPTION
**Pull request by jasnow**
Added simplecov for coverage analysis. Also updated README file.

Note coverage is not 100% (93.85%) because of the **if Rails::VERSION::MAJOR == 3** block in lib/setler/settings.rb file.

### CODE REVIEW

**Comment by ckdake** [comment]
cover_me was pulled as part of https://github.com/ckdake/setler/pull/28 but it looks like the README didn't get updated. Could you update the README as part of this too?

**Comment by jasnow** [comment]
>>  Could you update the README as part of this too?

Do not see cover_me mention in README, but I can change 'still 100%' to 'the same'. Is that okay?

**Comment by ckdake** [comment]
:+1:

**Comment by jasnow** [comment]
Anything else?

**Comment by jasnow** [comment]
Thanks

**Pull request merged**
