### PR TITLE
Add non-TravisCI changes to support multiple Rails versions

### PR DESCRIPTION
**Pull request by jasnow**
Add **non-TravisCI** changes to support multiple Rails versions (issues #33)
 * Added "appraisal" gem to gemspec file.
 * Added Appraisals file with Rails 3, 4, and 5/edge.
 * Run "appraisal install" to generate files in "gemfiles" directory.
 * Added Rails 3 code to lib/setler/settings.rb file.
 * Added "README-appraisal.rdoc" to show text changes after we add TravisCI support.

 * NOTE: No change to Gemfile, Rakefile, and .travis.yml files.

 * NOTE that you can still run "rake test" locally and on TravisCI.

### CODE REVIEW

**Comment by ckdake** [comment]
Is there a reason to have this README as a separate file or could we go ahead and make this change in the main one?

**Comment by jasnow** [comment]
>> Is there a reason to have this README as a separate file or could we go ahead and make this change in the main one?

This feature is not done (needs TravisCI part) so I did not want to change the external project information until it was done.

**Comment by ckdake** [comment]
Gotcha, are there instructions for what I need to do in Travis to get this all playing nice?

**Comment by jasnow** [comment]
>> Gotcha, are there instructions for what I need to do in Travis to get this all playing nice?

The large number of my previous commits were generally focused on trying to solve the Travis integration. I have not solved that integration so I decided to create this pull request which includes all but the Travis integration.  The Travis integration would come in a future pull request.

If you do not want this partial solution, just add a comment to this PR and I will close it.
Cheers....

**Comment by ckdake** [comment]
Lets done one of:

1. Split this into two pieces then, one for the partial solution and one for the Travis bit (with the new readme in the Travis PR only)
2. Add a "Coming Soon" part to the README with the Travis specific things that aren't ready yet

**Comment by jasnow** [comment]
I will adding the (2) "Coming Soon" section to the new README file. Then support above (1)  with this pull request

**Comment by jasnow** [comment]
Next we can replace original README with new version of README if you like the changes.
To see new version, use this: https://github.com/jasnow/setler/blob/master/README-appraisal.rdoc

**Comment by ckdake** [comment]
Looks good, If you remove the README-appraisal file from this PR, I'll merge this on in.

**Comment by jasnow** [comment]
Removing README-appraisal file as requested.

**Comment by jasnow** [comment]
THANKS !!!!

**Pull request merged**
